# Workflow name
name: Next.js CI Pipeline

# on mean is trigger start
on:
  push:
    branches: [main]

# jobs and steps 2nd Stpes
jobs:
  build-and-test:
    runs-on: unbuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cache Next.js Build and npm Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
            key: ${{ runner.os}}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}

          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Build Next.js App
        run: npm run build

    # CD
  deploy:
    # needs deploy wali jab he chalegi jab build-and-test job successfully complete ho jaye
    needs: build-and-test
    runs-on: ubuntu-latest
    # main branch per agar push ho to hi ye job chalegi
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Trigger Deployment
        # linux ka ek tool hota hain uska name hai curl mean is link
        run: curl -f  "${{secrets.RENDER_DEPLOY_HOOK}}"
